#!/bin/bash

# Help: https://jekyllrb.com/docs/ruby-101/

if [[ "$VENDOR" == "suse" ]]; then
	# OpenSUSE Tumbleweed doesn't have a simple jekyll package to install.
	# So use a GEM_HOME in the home directory instead of poluting the root gem dir.
	# GEM_HOME="${PWD}/.gem" gem install jekyll

	jekyll=`find "${PWD}/.gem/bin/" -name "jekyll*"` # ./.gem/bin/jekyll.ruby3.3
	GEM_HOME="${PWD}/.gem" "$jekyll" serve --livereload
else
	jekyll serve --livereload
fi
